image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - git config --global user.email "1787609016@qq.com"
  - git config --global user.name "whatseven"
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
